### PR TITLE
Feature/add derivation method

### PR DESCRIPTION
**Pull request by WillMcDGSK**
@PranjaliParnerkar Please review!
@paltusplintus FYI (or please also review if you have time!)
@Vidhisri56 @shannonhaughton  FYI

This PR is moving the DerivationMethod class from cldbe to tab2neo. It includes extended unit tests, bug fixes, extended documentation and an examples folder. Please make sure tab2neo unit tests pass as well as the unit tests for our repos that have tab2neo as a requirement. Please also check that MB works as before with applying derivation!

### CODE REVIEW

**Comment by WillMcDGSK** [comment]
> @WillMcDGSK The below test cases inside the derivation_method failed for me. Could you please check.
> 
> 1. test_derivation_method_factory.py - all the test cases
> 2. TestDelete - test_multiple_delete_method
> 3. test_link_nan.py - all the test cases
> 4. TestApply - test_load_get_method_metadata, test_apply_method_assign, test_apply_method_link
> 5. test_retrieve_json.py

@PranjaliParnerkar Could you please add some screenshots of how they fail? They run fine on my end.

**Comment by PranjaliParnerkar** [comment]
@WillMcDGSK While running MB, the github_write_dialog.py file under tab_derivation_method in cldnb is throwing error on line-6 as shown below.
`from derivation_method.derivation_method import DictDerivationMethod`

Its working fine when changed the import statement to
`from derivation_method import DictDerivationMethod`

**Comment by PranjaliParnerkar** [comment]
Please find the below error while running apply_stat for 'calculate_sum_stat_SAE_by_trt01_001' derivation.

Screenshot 2023-06-02 125108

Screenshot 2023-06-02 125139

Screenshot 2023-06-02 125205

**Comment by WillMcDGSK** [comment]
> **1.** While running MB, the github_write_dialog.py file under tab_derivation_method in cldnb is throwing error on line-6 as shown below. `from derivation_method.derivation_method import DictDerivationMethod`
> 
> Its working fine when changed the import statement to `from derivation_method import DictDerivationMethod`
> 
> **2.** Also got below error while running run_script method action- `ModuleNotFoundError: No module named 'derivation_method.scripts.study_specific_ops'` Please find the attached screenshot Screenshot 2023-06-02 123559

@PranjaliParnerkar For 1. you will need to uninstall tab2neo from your venv and reinstall from local again. This is because the setup.py file has changed with the addition of derivation method.

**Pull request merged**
